---
title: "Análisis exploratorio de datos"
date: "Marzo 2019"
output: 
  html_notebook
---


```{r setup}
library(tidyverse)
library(ggthemes)
library(ggfortify)
library(treemapify)
library(RColorBrewer)
library(shiny)
library(shinythemes)
library(shinycssloaders)
library(glue)
library(readxl)
library(DT)
library(magrittr)
```


### Treemap mundo. Cadenas y subcadenas

```{r}
# dataset <- read.delim('data/Export_agg_country_prod_yr.txt',sep = ',', encoding = 'UTF-8')
dataset <- read.delim('../dataset/Export_World_directo.csv',sep = ',', encoding = 'UTF-8')
#renombro las variables

dataset_summ <-dataset %>% 
  group_by(Cadena, Subcadena) %>% 
  summarise(value = sum(value, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(Subcadena = as.character(Subcadena))

dataset_summ$Subcadena[str_detect(dataset_summ$Subcadena, 'CTEOS')] <- 'LACTEOS'

dataset_summ %>% 
  ggplot(., aes(area = value, fill = Cadena, label = Subcadena, subgroup = Cadena)) + 
  geom_treemap(alpha = 1)+
  geom_treemap_subgroup_text(place = "bottomright", grow = T, alpha = 0.5, colour =
                               "black", fontface = "italic", min.size = 0) +
  geom_treemap_text(colour = "white", place = "topleft", reflow = T)+
  # labs(title= glue("Treemap {flow_filter}, {reportante}, year {nano}"))+
  # scale_fill_manual(values = colores)+
  theme_tufte()+
  theme(legend.position = "None",
        title = element_text(size = 18),
        strip.text = element_text(size=18))


ggsave('graficos/treemap_cadsubcad.png', width = 7,height = 7)
```



### Treemap mundo. Cadenas y usos

```{r}

dataset_summ_usos <-dataset %>% 
  group_by(Cadena, Flores) %>% 
  summarise(value = sum(value, na.rm = T)) %>% 
  ungroup() 

dataset_summ_usos %>% 
  ggplot(., aes(area = value, fill = Cadena, label = Flores, subgroup = Cadena)) + 
  geom_treemap(alpha = 1)+
  geom_treemap_subgroup_text(place = "bottomright", grow = T, alpha = 0.5, colour =
                               "black", fontface = "italic", min.size = 0) +
  geom_treemap_text(colour = "white", place = "topleft", reflow = T)+
  # labs(title= glue("Treemap {flow_filter}, {reportante}, year {nano}"))+
  # scale_fill_manual(values = colores)+
  theme_tufte()+
  theme(legend.position = "None",
        title = element_text(size = 18),
        strip.text = element_text(size=18))


ggsave('graficos/treemap_usos.png', width = 7,height = 7)
```


#### Treemap mundo. Paises receptores

```{r}
df <- readRDS('data/aggregated_trade.RDS')

countrycode_data <- countrycode::codelist %>% select(cldr.short.es_ar, cldr.short.en,iso3c,region,continent)
df <- left_join(df,countrycode_data 
                      %>% select(rt3ISO=iso3c, continent, cldr.short.es_ar)) %>% 
  na.omit(.)

df_summ_paieses <- df %>% 
  group_by(continent,cldr.short.es_ar,rgDesc) %>% 
  summarise(value = sum(TradeValue)) %>% 
  filter(rgDesc %in% c('Export', 'Import')) 
  
df_summ_paieses %>% 
ggplot(., aes(area = value, fill = continent, label = cldr.short.es_ar, subgroup = continent)) + 
  geom_treemap(alpha = 1, layout = "fixed")+
  geom_treemap_subgroup_text(place = "bottomright", grow = T, alpha = 0.5, colour =
                               "black", fontface = "italic", min.size = 0, layout = "fixed") +
  geom_treemap_text(colour = "white", place = "topleft", reflow = T, layout = "fixed")+
  theme_tufte()+
  theme(legend.position = "None",
        title = element_text(size = 18),
        strip.text = element_text(size=18))+
        facet_grid(.~rgDesc)


ggsave('graficos/treemap_paises.png', width = 7,height = 7)
```



###### treemaps usos

```{r}
dataset <- read_rds("ShinyApp/data_cadena.rds")
#renombro las variables
dataset <- dataset %>% 
  rename(reporter = Reporter, partner = Partner, year = Year, flow = TradeFlowName, value = TradeValue)

dataset <-   dataset %>%
  mutate(partner=case_when(partner=="RDM_Sudamerica_sin_China"~"Rest of the world \n (except China)",
                           partner=="Bolivia (Plurinational State of)" ~ "Bolivia",
                           TRUE ~ partner))


agregados <- c("Mercosur", "Sudamerica","RDM_Mercosur","RDM_Mercosur_sin_China","RDM_Sudamerica", "World")

dataset <- dataset %>% 
  filter(!partner %in% agregados)

```

```{r}
grow_treemap_usos <- function(data=dataset,nano= 2016, reportante = "Sudamerica",flow_filter = "Export",
                                download = F){
  
  usos <- unique(data$Flor)
  #Tomo toda la escala cromática, y eligo por k-means los colores más distintivos posibles
  colores <- c("#455930",  "#c057c5","#63b649","#6148b9","#c49d35", "grey")
  names(colores) <- usos
  
  
  if (reportante == "Sudamerica") {
    data_filt <-   data %>% 
      filter(year == nano,flow== flow_filter)
    
  }else{
    data_filt <-   data %>% 
      filter(reporter==reportante, year == nano, flow == flow_filter)
  }
  if (nrow(data_filt)==0) {
    return(ggplot()+
             ggtitle(paste("No hay data para ",reportante,", ",nano)))
    
  }else{
    
   g <-  data_filt  %>% 
      mutate(RDM = case_when(partner=="Rest of the world \n (except China)"~partner,
                             partner=="China"~partner,
                             TRUE ~ "South America"),
             RDM = factor(RDM, levels = c("South America","Rest of the world \n (except China)","China"))) %>%
      group_by(RDM,Flor) %>%
      summarise(value = sum(value)) %>% 
      ggplot(., aes(area = value, fill = Flor, label = Flor)) + 
      geom_treemap(alpha = 1)+
      geom_treemap_text(colour = "white", place = "topleft", reflow = T)+
      facet_wrap(~RDM, ncol = 2)+
      scale_fill_manual(values = colores)+
      theme_tufte()+
      theme(legend.position = "None",
            title = element_text(size = 20),
            strip.text = element_text(size=20))
    
    if (!download) {
      g <- g+ labs(title= glue("Treemap {flow_filter}, {reportante}, year {nano}"))
        
    }
    g
    
  }
}

```

```{r}
grow_treemap_usos(download = T)
ggsave("graficos/treemaps_usos2016.png", scale = 2)
```

```{r}
grow_treemap_usos(flow_filter = "Import", download = T)

ggsave("graficos/treemaps_usos2016_impos.png", scale = 2)

```

