---
title: "Análisis composición cadenas"
output: 
  html_notebook: 
    code_folding: hide
    theme: paper
    toc: yes
    toc_depth: 2
    toc_float: yes
---


```{r}
library(tidyverse)
library(ggridges)
library(ggthemes)
library(readxl)
library(directlabels)

```


```{r message=FALSE, warning=FALSE}
S3_cadenas = read_csv("../dataset/correspondencias/S3_cadenas.csv")
```

# 30 componentes

```{r}
componentes <- read_csv("results/Dist_cadenas30.csv") %>% 
  mutate(componente = 1:nrow(.)) %>% 
  select(componente, everything()) %>% 
  gather(S3, prop, 2:ncol(.))
```

## S3 1 dígito
Distribución a 1 dígito
```{r, fig.height=20, fig.width=10}
componentes %>% 
  mutate(S31D = substr(S3,1,1)) %>% 
  group_by(componente,S31D) %>% 
  summarise(prop = sum(prop)) %>% 
ggplot(., aes(x = S31D, y = prop, fill =factor(componente))) + 
  geom_col()+
  facet_grid(componente~., scales = "free")+
  theme_minimal()+
  theme(legend.position = "none",
        text = element_text(size= 12),
        axis.text.x = element_text(vjust = 0.5, size = 12),
        axis.ticks.x = element_blank(),
        strip.text.y = element_text(angle = 0, size = 12))

```




## TOP SITC 

```{r, fig.height=15, fig.width=7}
componentes %>% 
  mutate(S31D = substr(S3,1,1)) %>% 
  group_by(componente) %>% 
  arrange(-prop) %>% 
  mutate(csum = cumsum(prop)) %>% 
  filter(csum<.5) %>% 
  mutate(S31D = substr(S3,1,1)) %>% 
  group_by(componente,S31D) %>% 
  summarise(prop = sum(prop)) %>% 
ggplot(., aes(x = S31D, y = prop, fill =factor(componente))) + 
  geom_col()+
  facet_grid(componente~., scales = "free")+
  theme_minimal()+
  theme(legend.position = "none",
        text = element_text(size= 12),
        axis.text.x = element_text( vjust = 0.5, size = 12),
        axis.ticks.x = element_blank(),
        strip.text.y = element_text(angle = 0, size = 12))

```





## cadenas

```{r, fig.height=20, fig.width=10}
componentes %>% 
  left_join(.,S3_cadenas, by="S3"  ) %>% 
  group_by(componente, Cadena) %>% 
  summarise(prop=sum(prop)) %>% 
  ggplot(., aes(x = Cadena, y = prop, fill =factor(componente))) + 
  geom_col()+
  facet_grid(componente~., scales = "free")+
  theme_minimal()+
  theme(legend.position = "none",
        text = element_text(size= 10),
        axis.ticks.x = element_line(),
        axis.text.x = element_text(angle=35, vjust = .75, size = 10),
        strip.text.y = element_text(angle = 0, size = 12))
```


## TOP cadenas


```{r, fig.height=15 , fig.width=15}
componentes %>% 
  mutate(S31D = substr(S3,1,1)) %>% 
  group_by(componente) %>% 
  arrange(-prop) %>% 
  mutate(csum = cumsum(prop)) %>% 
  filter(csum<.5) %>%
  left_join(.,S3_cadenas, by="S3"  ) %>% 
  mutate(Cadena = tolower(Cadena)) %>% 
  group_by(componente, Cadena) %>% 
  summarise(prop=sum(prop)) %>% 
  ggplot(., aes(x = Cadena, y = prop, fill =factor(componente))) + 
  geom_col()+
  facet_wrap(componente~., scales = "free", ncol = 4)+
  theme_minimal()+
  theme(legend.position = "none",
        text = element_text(),
        axis.ticks.x = element_line(),
        axis.text.x = element_text(angle=35, vjust = .75, size = 11),
        strip.text.y = element_text(angle = 0))
```









